import os

file_path = 'c:/Users/Asus/Downloads/เอกสหกรุ๊ป/FuelVerify-AI/backend/main.py'
with open(file_path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

new_content = lines[:1396] # Keep up to line 1396 (index 1395)

# Append correct functions
new_content.extend([
'    def _apply_typhoon_result(ocr_text: str, variant: Image.Image, used_angle: int, log_prefix: str) -> dict:\n',
'        nonlocal best_score, best_attempt_data, best_ocr_text, best_img_b64, best_angle\n',
'        ai_data = _parse_slip_text(ocr_text)\n',
'        attempt_score = _score(ai_data)\n',
'        for key in merged_data:\n',
'            if merged_data[key] is None and ai_data.get(key) is not None:\n',
'                merged_data[key] = ai_data[key]\n',
'        if attempt_score > best_score:\n',
'            best_score = attempt_score\n',
'            best_attempt_data = ai_data.copy()\n',
'            best_ocr_text = ocr_text or ""\n',
'            best_angle = used_angle\n',
'            buffered2 = io.BytesIO()\n',
'            variant.save(buffered2, format="JPEG", quality=85)\n',
'            best_img_b64 = base64.b64encode(buffered2.getvalue()).decode("ascii")\n',
'            print(f"✅ Best OCR updated: {log_prefix} angle={used_angle}° score={attempt_score}")\n',
'        return ai_data\n',
'\n',
'    variant0 = img_rgb\n',
'    for attempt in range(1, max_retries + 1):\n',
'        if all(merged_data[k] is not None for k in merged_data): break\n',
'        try:\n',
'            ocr_text = _typhoon_ocr_text(variant0)\n',
'            if not ocr_text: continue\n',
'            _apply_typhoon_result(ocr_text, variant0, 0, f"attempt={attempt}")\n',
'        except Exception as e: print(f"Error: {e}"); _mark_typhoon_fail()\n',
'\n',
'    if SLIP_ROTATION_FALLBACK:\n',
'        for angle in (90, 180, 270):\n',
'            if all(merged_data[k] is not None for k in merged_data): break\n',
'            variant = img_rgb.rotate(angle, expand=True).convert("RGB")\n',
'            try:\n',
'                ocr_text = _typhoon_ocr_text(variant)\n',
'                if ocr_text: _apply_typhoon_result(ocr_text, variant, angle, f"rotation={angle}°")\n',
'            except Exception: pass\n',
'\n',
'    final_data = best_attempt_data.copy()\n',
'    for k in final_data: \n',
'        if final_data.get(k) is None: final_data[k] = merged_data.get(k)\n',
'    if pre_parsed:\n',
'        for k in final_data: \n',
'            if final_data.get(k) is None: final_data[k] = pre_parsed.get(k)\n',
'\n',
'    tesseract_raw = ""\n',
'    if any(final_data.get(k) is None for k in ("last4", "merchant", "amount")):\n',
'        tess_img = img_rgb if best_angle == 0 else img_rgb.rotate(best_angle, expand=True).convert("RGB")\n',
'        tesseract_raw, tess_parsed = _tesseract_slip_supplement(tess_img)\n',
'        if tess_parsed:\n',
'            for k in final_data:\n',
'                if final_data.get(k) is None: final_data[k] = tess_parsed.get(k)\n',
'\n',
'    roi_raw = ""\n',
'    if final_data.get("last4") is None or final_data.get("amount") is None:\n',
'        roi_raw, roi_parsed = _tesseract_slip_roi_boost(img_rgb if best_angle == 0 else img_rgb.rotate(best_angle, expand=True).convert("RGB"))\n',
'        if roi_parsed:\n',
'            for k in ("last4", "merchant"): \n',
'                if final_data.get(k) is None: final_data[k] = roi_parsed.get(k)\n',
'\n',
'    quality_text = (best_ocr_text or "") + "\\n" + (pre_ocr_text or "") + "\\n" + (tesseract_raw or "") + "\\n" + (roi_raw or "")\n',
'    quality = _build_page_quality(quality_text.strip(), final_data)\n',
'\n',
'    return {\n',
'        "image": f"data:image/jpeg;base64,{best_img_b64}",\n',
'        "values": final_data,\n',
'        "highlights": {k: None for k in final_data},\n',
'        "quality": quality\n',
'    }\n',
'\n',
'progress_store = {}\n',
'\n',
'def extract_slip_preview(filename: str, content: bytes, task_id: str = None):\n',
'    api_url = (os.environ.get("TYPHOON_OCR_URL") or "https://api.opentyphoon.ai/v1/ocr").strip()\n',
'    api_key = (os.environ.get("TYPHOON_API_KEY") or os.environ.get("OPENTYPHOON_API_KEY") or "").strip()\n',
'    if not api_key: raise HTTPException(status_code=503, detail="Missing API Key")\n',
'    lower = (filename or "").lower(); source_pdf_bytes = content; pre_texts = []\n',
'    if lower.endswith(".pdf"):\n',
'        has_text_layer = _pdf_has_text_layer(content)\n',
'        if not has_text_layer:\n',
'            provider = SLIP_TEXTLAYER_PROVIDER\n',
'            if provider == "auto": provider = "ilovepdf" if ILOVEPDF_PUBLIC_KEY else "ocrmypdf"\n',
'            if provider == "ilovepdf":\n',
'                source_pdf_bytes, pre_texts = _ilovepdf_add_text_layer(content, filename=(filename or "input.pdf"))\n',
'                if not source_pdf_bytes: source_pdf_bytes, pre_texts = _ocrmypdf_add_text_layer(content)\n',
'            else: source_pdf_bytes, pre_texts = _ocrmypdf_add_text_layer(content)\n',
'        if not source_pdf_bytes: source_pdf_bytes = content\n',
'    images = _images_from_upload_bytes(filename, source_pdf_bytes)\n',
'    total_pages = len(images)\n',
'    if not pre_texts: pre_texts = [""] * total_pages\n',
'    if task_id: progress_store[task_id] = {"current": 0, "total": total_pages}\n',
'    workers = max(1, min(SLIP_OCR_WORKERS, total_pages, 8))\n',
'    typhoon_breaker = {"fail_streak": 0, "open": False}; typhoon_breaker_lock = threading.Lock()\n',
'    def _run_page(idx: int, page_img):\n',
'        return idx, _ocr_single_image(page_img, api_url, api_key, pre_ocr_text=pre_texts[idx] if idx < len(pre_texts) else "", breaker_state=typhoon_breaker, breaker_lock=typhoon_breaker_lock)\n',
'    pages = [None] * total_pages\n',
'    with ThreadPoolExecutor(max_workers=workers) as pool:\n',
'        future_map = {pool.submit(_run_page, i, img): i for i, img in enumerate(images)}\n',
'        done = 0\n',
'        for fut in as_completed(future_map):\n',
'            idx, pr = fut.result(); pages[idx] = pr; done += 1\n',
'            if task_id: progress_store[task_id] = {"current": done, "total": total_pages}\n',
'    all_last4 = [p["values"].get("last4") for p in pages if p["values"].get("last4")]\n',
'    if all_last4:\n',
'        common = list(set(all_last4))[0] if len(set(all_last4)) == 1 else None\n',
'        for p in pages: \n',
'            if p["values"].get("last4") is None: p["values"]["last4"] = common\n',
'    if task_id and task_id in progress_store: del progress_store[task_id]\n',
'    return {"total_pages": total_pages, "pages": pages}\n',
'\n',
'@app.post("/upload")\n',
'def upload_pdf(files: List[UploadFile] = File(...)):\n',
'    for f in files:\n',
'        if not (f.filename or "").lower().endswith(".pdf"): raise HTTPException(status_code=400, detail="Invalid file type")\n',
'    try:\n',
'        bbl_merged_data = {}; bbl_summary = {"previous_balance": "0.00", "current_total": "0.00"}; kbank_data = []\n',
'        for f in files:\n',
'            content = f.file.read(); f.file.seek(0); text_preview = ""\n',
'            with pdfplumber.open(io.BytesIO(content)) as pdf:\n',
'                for p in pdf.pages[:2]: text_preview += (p.extract_text() or "")\n',
'            if "BANGKOK BANK" in text_preview.upper() or "ธนาคารกรุงเทพ" in text_preview:\n',
'                res_obj = extract_bbl_ocr(content); res = res_obj.get("data", []); s = res_obj.get("summary", {})\n',
'                if s.get("previous_balance") != "0.00": bbl_summary["previous_balance"] = s.get("previous_balance")\n',
'                if s.get("current_total") != "0.00": bbl_summary["current_total"] = s.get("current_total")\n',
'                for card in res:\n',
'                    cid = card.get("card_id")\n',
'                    if cid not in bbl_merged_data: bbl_merged_data[cid] = card\n',
'                    else:\n',
'                        existing = bbl_merged_data[cid]\n',
'                        if card.get("transactions"): existing["transactions"].extend(card["transactions"])\n',
'                        existing["transaction_count"] = len(existing["transactions"])\n',
'                        if card.get("balance") != "0.00": existing["balance"] = card["balance"]\n',
'            else: kbank_data.extend(extract_kasikorn_ocr(content))\n',
'        final = sorted(bbl_merged_data.values(), key=lambda x: str(x.get("card_id", ""))) + kbank_data\n',
'        return {"filename": ", ".join([f.filename for f in files]), "count": len(final), "data": final, "summary": bbl_summary if bbl_merged_data else None}\n',
'    except Exception as e: import traceback; traceback.print_exc(); raise HTTPException(status_code=500, detail=str(e))\n',
'\n',
'def extract_bbl_ocr(pdf_bytes):\n',
'    data_rows = []; card_map = {}\n',
'    with pdfplumber.open(io.BytesIO(pdf_bytes)) as pdf:\n',
'        all_text = ""\n',
'        for page in pdf.pages: all_text += (page.extract_text() or "") + "\\n---PAGE_BREAK---\\n"\n',
'        num_pattern = r\'([\\d,]+\\s*\\.\\s*\\d{2})\'\n',
'        global_prev_bal = "0.00"; global_curr_total = "0.00"\n',
'        m_prev = re.search(num_pattern + r\'[\\s\\S]{0,40}Previous Balance\', all_text, re.IGNORECASE)\n',
'        if m_prev: global_prev_bal = re.sub(r\'\\s+\', \'\', m_prev.group(1))\n',
'        m_curr = re.search(r\'Total\\s+[\\d,.\\s]+\\s+\' + num_pattern + r\'\\s+-\\s+\' + num_pattern, all_text, re.IGNORECASE)\n',
'        if m_curr: global_curr_total = re.sub(r\'\\s+\', \'\', m_curr.group(2))\n',
'        for line in all_text.split(\'\\n\'):\n',
'            m = re.search(r\'(\\d{4}\\s+00xx\\s+xxxx\\s+(\\d{4}))[^\\n]*?\\s+([\\d,]+\\s*\\.?\\s*\\d*)\\s+Baht[^\\n]*?([\\d,]+\\s*\\.\\s*\\d{2})\', line)\n',
'            if m:\n',
'                card_id = m.group(2)\n',
'                if card_id not in card_map:\n',
'                    data_rows.append({"card_no": m.group(1), "card_id": card_id, "account_name": f"CARD {card_id}", "credit_limit": re.sub(r\'\\s+\', \'\', m.group(3)), "balance": m.group(4), "min_payment": "0.00", "previous_balance": "0.00", "total_balance_calc": m.group(4), "transaction_count": 0, "transactions": []})\n',
'                    card_map[card_id] = len(data_rows) - 1\n',
'        sections = re.split(r\'Account\\s+Details|รายละเอียดรายการใช้จ่าย\', all_text, flags=re.IGNORECASE)\n',
'        for section in sections[1:]:\n',
'            m_card = re.search(r\'หมายเลขบัตร\\s+([\\d\\sXx]+)\', section)\n',
'            if not m_card: continue\n',
'            clean_digits = re.sub(r\'[^\\d]+\', \'\', m_card.group(1)); card_id = clean_digits[-4:]\n',
'            if card_id not in card_map:\n',
'                data_rows.append({"card_no": m_card.group(1).strip(), "card_id": card_id, "account_name": f"CARD {card_id}", "credit_limit": "0.00", "balance": "0.00", "min_payment": "0.00", "previous_balance": "0.00", "total_balance_calc": "0.00", "transaction_count": 0, "transactions": []})\n',
'                card_map[card_id] = len(data_rows) - 1\n',
'            tid = card_map[card_id]; m_lim = re.search(r\'วงเงิน\\s+([\\d,]+)\', section)\n',
'            if m_lim: data_rows[tid]["credit_limit"] = m_lim.group(1).replace(\',\', \'\')\n',
'            txn_lines = section.split(\'\\n\')\n',
'            for i, line in enumerate(txn_lines):\n',
'                m_txn = re.search(r\'(\\d{2}/\\d{2}/\\d{4})\\s+(\\d{2}:\\d{2})\\s+(\\d{2}/\\d{2}/\\d{4})\\s+(\\d+)\\s+(.*?)\\s+(\\d+)\\s+(.*?)\\s+([\\d,]+\\.\\d{2})\\s+([\\d,]+\\.\\d{2})\\s+([\\d,]+\\.\\d{2})\', line)\n',
'                if m_txn:\n',
'                    main_desc, product, amount = m_txn.group(5).strip(), m_txn.group(7).strip(), m_txn.group(10)\n',
'                    sub = []; branch = ""\n',
'                    for j in range(1, 3):\n',
'                        if i+j < len(txn_lines):\n',
'                            nl = txn_lines[i+j].strip()\n',
'                            if re.match(r\'\\d{2}/\\d{2}/\\d{4}\', nl) or "ยอดเงินรวม" in nl or "PAYMENT" in nl: break\n',
'                            sub.append(nl)\n',
'                    if sub: branch = sub[-1]; desc = " ".join([main_desc] + sub[:-1]) if len(sub) > 1 else main_desc\n',
'                    else: desc = main_desc\n',
'                    data_rows[tid]["transactions"].append({"date": m_txn.group(1), "post_date": m_txn.group(3), "desc": desc.strip(), "branch": branch.strip(), "type": product, "amount": amount})\n',
'                pmt = re.search(r\'(\\d{2}/\\d{2}/\\d{4})\\s+(\\d{2}/\\d{2}/\\d{4})\\s+PAYMENT\\s+([\\d,]+\\.\\d{2}-)\', line)\n',
'                if pmt: data_rows[tid]["transactions"].append({"date": pmt.group(1), "post_date": pmt.group(2), "desc": "ชำระเงินคืน", "branch": "", "type": "ชำระเงิน", "amount": pmt.group(3).replace(\'-\', \'\')})\n',
'            m_foot = re.search(r\'ยอดเงินรวม.*?\\(Total.*?Amount\\)\\s*([\\d,]+\\.\\d{2})\', section, re.IGNORECASE)\n',
'            if m_foot: data_rows[tid]["balance"] = data_rows[tid]["total_balance_calc"] = m_foot.group(1).replace(\',\', \'\')\n',
'            data_rows[tid]["transaction_count"] = len(data_rows[tid]["transactions"])\n',
'    return {"data": data_rows, "summary": {"previous_balance": global_prev_bal, "current_total": global_curr_total}}\n',
'\n',
'@app.get("/upload-slip-progress")\n',
'def get_slip_progress(task_id: str): return progress_store.get(task_id, {"current": 0, "total": 0})\n',
'\n',
'@app.post("/upload-slip")\n',
'def upload_slip(file: UploadFile = File(...), task_id: str = None):\n',
'    try:\n',
'        content = file.file.read(); extracted = extract_slip_preview(file.filename, content, task_id)\n',
'        return {"filename": file.filename, **extracted}\n',
'    except Exception as e: raise HTTPException(status_code=500, detail=str(e))\n',
'\n',
'@app.get("/api/records")\n',
'def get_records():\n',
'    conn = sqlite3.connect(DB_PATH); conn.row_factory = sqlite3.Row; c = conn.cursor()\n',
'    c.execute("SELECT id, name, date, type, data, hidden, created_at FROM records WHERE hidden = 0 ORDER BY created_at DESC")\n',
'    rows = c.fetchall(); results = []\n',
'    for r in rows:\n',
'        try: results.append({**json.loads(r["data"]), "created_at": r["created_at"], "hidden": r["hidden"]})\n',
'        except: pass\n',
'    conn.close(); return results\n',
'\n',
'@app.get("/api/records/{id}")\n',
'def get_record_detail(id: str):\n',
'    conn = sqlite3.connect(DB_PATH); conn.row_factory = sqlite3.Row; c = conn.cursor()\n',
'    c.execute("SELECT data FROM records WHERE id = ?", (id,)); r = c.fetchone()\n',
'    if not r: conn.close(); raise HTTPException(status_code=404, detail="Not found")\n',
'    record = json.loads(r["data"])\n',
'    c.execute("SELECT data FROM slip_blobs WHERE id = ?", (id,)); sb = c.fetchone()\n',
'    if sb: record["slipResult"] = json.loads(sb["data"])\n',
'    conn.close(); return record\n',
'\n',
'@app.post("/api/records")\n',
'async def save_record(record: dict):\n',
'    rid = record.get("id"); slip = record.pop("slipResult", None); conn = sqlite3.connect(DB_PATH); c = conn.cursor()\n',
'    c.execute("SELECT hidden FROM records WHERE id = ?", (rid,)); ex = c.fetchone(); hid = ex[0] if ex else 0\n',
'    c.execute("INSERT OR REPLACE INTO records (id, name, date, type, data, hidden) VALUES (?, ?, ?, ?, ?, ?)", (rid, record.get("name"), record.get("date"), record.get("type"), json.dumps(record), hid))\n',
'    if slip: c.execute("INSERT OR REPLACE INTO slip_blobs (id, data) VALUES (?, ?)", (rid, json.dumps(slip)))\n',
'    else: c.execute("DELETE FROM slip_blobs WHERE id = ?", (rid,))\n',
'    conn.commit(); conn.close(); return {"status": "success", "id": rid}\n',
'\n',
'@app.delete("/api/records/{id}")\n',
'def delete_record(id: str):\n',
'    conn = sqlite3.connect(DB_PATH); c = conn.cursor(); c.execute("UPDATE records SET hidden = 1 WHERE id = ?", (id,)); conn.commit(); conn.close(); return {"status": "hidden"}\n',
'\n',
'if __name__ == "__main__":\n',
'    import uvicorn\n',
'    uvicorn.run(app, host="127.0.0.1", port=int(os.environ.get("PORT", "5004")))\n',
])

# Now append helpers that are at the bottom of the original file (if they survive)
# Actually I'll append them manually if I know they are missing.
# Let's see what's left after line 1396.
# I'll just write it and then check.

with open(file_path, 'w', encoding='utf-8') as f:
    f.writelines(new_content)
